apiVersion: v1
kind: Config
preferences: {}

clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpReE56Y3hNalF3SGhjTk1qWXdNekl5TVRBMU9EUTBXaGNOTXpZd016RTVNVEExT0RRMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpReE56Y3hNalF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTMmRsYnk3ZXZ2dVV2K3ZKeE1CUFB5MkFmUTdHNjYxUnhsTlJ4U0ZRZEoKZXpuU1JjTGNsKzBxUlRNM042eDhOWDczTlg2UE5CKzZkT0E4MitRQXQxY1lvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVFzbHFOdEF5bkpkWGlkTmpvUjMxCktSdno0Wll3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU40L20waFNiUE5EUEg1YzRjVk01akJGRml1M3dWL1IKbitwY1dBT1ZyRkZvQWlFQTJJOFNuZUp5VC80QlpBVDhqOHNHa0hvUHJNamdheGx5UGYyR3ZRd25Rc1k9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://k3s.gearsy.lan:6443
    name: cicd
users:
  - name: cicd-user
    user:
      as-user-extra: {}
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImZqakp1SDhFdWVkZjNiQnl2TVR4aTh0NVBFWkQ2RTZSWGFkVEh0VDJKa2sifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJteS1taWNyby1zZXJ2aWNlIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImNpY2Qtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiY2ljZC1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImY2MzZiYzAyLTEzYzAtNDEzOS1hNGVkLWRmOWRlZjIwNGEyOSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpteS1taWNyby1zZXJ2aWNlOmNpY2Qtc2EifQ.1y2WxjUzUOuwVuEz0kbTg1PodinsqfAKYQozfuvTItv2XrRCEQr_vw-7pt_M14PzohpmdqbWRV5LxsGmuRbvUndn1gVQ6GR2050Ey4wuDeDOe9ChjI6iq0y25EvLZAWWEv2zdxV4a6VErTuS3KbrHPkMgGFYMfU0lP59D2EfYcDyoZCAG1azbdWSkwibiNR_ukEdnQzKSf76jvAMhgJu97DyKeAmCsp0MQa6BwO5XUtKlMA-5agFvmwz5JpTSe3rZpQgeK7-XISxaf81huFEPMuLKTX4FslG6xjAigFUAbP0to9gVQpxNOOFoK9MzKSt1Ibj5tgGo5qIvOunuVBDow

contexts:
  - context:
      cluster: default
      namespace: default
      user: cicd-user
    name: default
current-context: default